---
- name: add-host-add-net
  hosts: check_point
  vars_files: ... 
  connection: httpapi
  tasks:
    - name: Create host object
      check_point.mgmt.cp_mgmt_host:
        name: "{{cp_mgmt_host['name']}}"
        ip_address: "{{cp_mgmt_host['ip']}}"
        state: "{{cp_mgmt_host['state']}}"
        auto_publish_session: "{{cp_mgmt_host['auto_publish_sesion']}}"
    - name: add-network_1
      check_point.mgmt.cp_mgmt_network:
        name: "{{cp_mgmt_net['name']}}"
        state: "{{cp_mgmt_net['state']}}"
        subnet: "{{cp_mgmt_net['subnet']}}"
        subnet_mask: "{{cp_mgmt_net['subnet_mask']}}"
        nat_settings:
          auto_rule: yes
          hide_behind: ip-address
          ip_address: 192.100.100.100
          method: hide
        auto_publish_session: yes
