---
- name: add-host-add-net
  hosts: check_point
  connection: httpapi
  tasks:
    - name: Create host object
      check_point.mgmt.cp_mgmt_host:
        name: New_host_1
        ip_address: 192.168.44.44
        state: present
        auto_publish_session: yes
        color: light green
    - name: add-network_1
      check_point.mgmt.cp_mgmt_network:
        name: New_net_1
        state: present
        subnet: 192.168.20.0
        subnet_mask: 255.255.255.0
        color: light green
        nat_settings:
          auto_rule: yes
          hide_behind: ip-address
          ip_address: 192.100.100.100
          method: hide
        auto_publish_session: yes
