---
- name: Login
  hosts: 127.0.0.1
  tasks:
    - name: login
      uri:
        url: "https://console-ds-smartcheck.apps.cluster-c18f.c18f.example.opentlc.com/api/sessions"
        validate_certs: false
        method: POST
        body_format: json
        status_code: 201
        body:
          user:
            userID: "{{ user }}"
            password: "{{ pass }}"
      register: loginoutput

    - set_fact:
        token: "Bearer {{ loginoutput.json.token }}"

- name: start_check_image
  hosts: 127.0.0.1
  tasks:
    - name: start_check_image
      uri:
        url: "https://console-ds-smartcheck.apps.cluster-c18f.c18f.example.opentlc.com/api/scans"
        validate_certs: false
        method: POST
        body_format: json
        status_code: 201
        headers:
           Authorization: "{{ token }}"
        body:
          source:
            type: "docker"
            digest: "sha256:506b188c0abe2ae3c1561bbff7ce50284de2a241eff5da6f528a3a024871c606"
            registry: "default-route-openshift-image-registry.apps.cluster-c18f.c18f.example.opentlc.com"
            repository: "openshift/golang:latest"

- name: result_check_image
  hosts: 127.0.0.1
  tasks:
    - name: pause
      pause:
        minutes: 2
    - name: start_check_image
      uri:
        url: "https://console-ds-smartcheck.apps.cluster-c18f.c18f.example.opentlc.com/api/scans?digest=sha256:506b188c0abe2ae3c1561bbff7ce50284de2a241eff5da6f528a3a024871c606"
        validate_certs: false
        method: GET
        body_format: json
        headers:
           Authorization: "{{ token }}"
