---
- name: jira
  hosts: 127.0.0.1
  tasks:
    - name: get issue
      uri:
        url: "http://10.10.30.35:8080/rest/servicedeskapi/request/FIR-2?expand=requestType"
        method: GET
        force_basic_auth: yes
        body_format: json
        user: "Loki"
        password: "QAZqaz123"
      register: loginoutput

    - set_fact:
       issue: "{{ loginoutput.json | json_query(\"requestFieldValues[?fieldId=='description'].value\") }}"
    - debug:
        msg: "{{ issue }}"
    - set_fact:
       ip: "{{ issue[0] | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"
    - set_fact:
        sourse: "{{ ip[0] }}"
        destination: "{{ ip[1] }}"
