---
- name: terraform
  hosts: 127.0.0.1
  tasks:
    - terraform:
        project_path: "/home/ozz/yandex"
        state: present
      register: loginoutput

    - set_fact:
        cp_gate_ip: "{{ loginoutput.outputs.internal_ip_address_cp_gw.value }}"
        cp_gate_name: "{{ loginoutput.outputs.name_cp_gw.value }}"

    - debug:
        msg: "{{ cp_gate_name }}"
