---
- name: terraform
  hosts: 127.0.0.1
  tasks:
    - terraform:
        project_path: "/var/lib/awx/projects/_8__second/yandex"
        state: present
      register: loginoutput

    - set_fact:
        cp_gate_ip: "{{ loginoutput.outputs.internal_ip_address_cp_gw\-public\-private\-net\-1.value }}"
        cp_gate_name: "{{ loginoutput.outputs.name_cp_gw.value }}"

    - name: work with cp ips
      include_tasks: cp_yandex_base_short.yml
