---
- name: terraform
  hosts: 127.0.0.1
  tasks:
    - terraform:
        project_path: "/var/lib/awx/projects/_8__second/yandex"
        state: absent
      register: loginoutput

#    - debug:
#        msg: "{{ loginoutput }}"

    - name: cp_yandex_base_remove
      include_tasks: cp_yandex_base_remove.yml
